version: "3.9"

services: 
  web:
    container_name: sms-jackpot-api
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes: 
      - .:/app
    ports: 
      - 3000:3000 
    restart: on-failure
    environment:
      - PORT=3000
      - DB_DATABASE=jackpot
      - DB_PASSWORD=824Kjd13%
      - DB_USERNAME=root
      - DB_PORT=3307
      - DB_HOST=db
  db:
    container_name: mysql8
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 824Kjd13%
      MYSQL_DATABASE: jackpot
      MYSQL_PASSWORD: 824Kjd13%
      MYSQL_USERNAME: root
    ports:
      - 3307:3306
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume: